[2022-07-08 04:59:49,938] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: sql_demo.createtable_task manual__2022-07-08T04:59:49.206631+00:00 [queued]>
[2022-07-08 04:59:49,944] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: sql_demo.createtable_task manual__2022-07-08T04:59:49.206631+00:00 [queued]>
[2022-07-08 04:59:49,944] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-07-08 04:59:49,944] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-07-08 04:59:49,944] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-07-08 04:59:49,950] {taskinstance.py:1270} INFO - Executing <Task(MySqlOperator): createtable_task> on 2022-07-08 04:59:49.206631+00:00
[2022-07-08 04:59:49,953] {standard_task_runner.py:52} INFO - Started process 1127 to run task
[2022-07-08 04:59:49,955] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sql_demo', 'createtable_task', 'manual__2022-07-08T04:59:49.206631+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/sql_demo.py', '--cfg-path', '/tmp/tmpa7169efo', '--error-file', '/tmp/tmpk_80zlrv']
[2022-07-08 04:59:49,955] {standard_task_runner.py:80} INFO - Job 5: Subtask createtable_task
[2022-07-08 04:59:49,984] {logging_mixin.py:109} INFO - Running <TaskInstance: sql_demo.createtable_task manual__2022-07-08T04:59:49.206631+00:00 [running]> on host 6a15fbc57503
[2022-07-08 04:59:50,021] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sql_demo
AIRFLOW_CTX_TASK_ID=createtable_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-08T04:59:49.206631+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-08T04:59:49.206631+00:00
[2022-07-08 04:59:50,021] {mysql.py:82} INFO - Executing: 
create database if not exists dezyre_db;
use dezyre_db;

create table if not exists `dezyre_db`.`employees`
(
emp_id int auto_increment primary key,
first_name varchar(500) NOT null,
last_name varchar(500) NOT null,
hire_date date,
job_id varchar(225),
salary DECIMAL(7,2),
commission_pct DECIMAL(6,2),
manager_id int,
dept_id int
);
[2022-07-08 04:59:50,037] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 84, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 198, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 158, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 68, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 410, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `local_mysql` isn't defined
[2022-07-08 04:59:50,041] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=sql_demo, task_id=createtable_task, execution_date=20220708T045949, start_date=20220708T045949, end_date=20220708T045950
[2022-07-08 04:59:50,048] {standard_task_runner.py:98} ERROR - Failed to execute job 5 for task createtable_task (The conn_id `local_mysql` isn't defined; 1127)
[2022-07-08 04:59:50,087] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-08 04:59:50,136] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
