[2022-07-01 04:36:52,787] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-06-30T00:00:00+00:00 [queued]>
[2022-07-01 04:36:52,794] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-06-30T00:00:00+00:00 [queued]>
[2022-07-01 04:36:52,794] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-07-01 04:36:52,794] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-07-01 04:36:52,794] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-07-01 04:36:52,801] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-06-30 00:00:00+00:00
[2022-07-01 04:36:52,805] {standard_task_runner.py:52} INFO - Started process 4353 to run task
[2022-07-01 04:36:52,807] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-06-30T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/second_1.py', '--cfg-path', '/tmp/tmpe2yobem1', '--error-file', '/tmp/tmpa5ak6001']
[2022-07-01 04:36:52,807] {standard_task_runner.py:80} INFO - Job 33: Subtask inaccurate
[2022-07-01 04:36:52,840] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-06-30T00:00:00+00:00 [running]> on host cb1ba423fa3f
[2022-07-01 04:36:52,874] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-06-30T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-30T00:00:00+00:00
[2022-07-01 04:36:52,875] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-01 04:36:52,875] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-07-01 04:36:52,882] {subprocess.py:85} INFO - Output:
[2022-07-01 04:36:52,883] {subprocess.py:89} INFO - inaccurate
[2022-07-01 04:36:52,883] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-01 04:36:52,898] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220630T000000, start_date=20220701T043652, end_date=20220701T043652
[2022-07-01 04:36:52,938] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-01 04:36:52,973] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
