[2022-07-14 13:18:45,641] {processor.py:163} INFO - Started process (PID=44619) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:18:45,641] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:18:45,642] {logging_mixin.py:109} INFO - [2022-07-14 13:18:45,642] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:18:45,645] {logging_mixin.py:109} INFO - [2022-07-14 13:18:45,645] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:18:45,646] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:18:45,658] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.020 seconds
[2022-07-14 13:19:15,820] {processor.py:163} INFO - Started process (PID=44694) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:19:15,821] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:19:15,821] {logging_mixin.py:109} INFO - [2022-07-14 13:19:15,821] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:19:15,827] {logging_mixin.py:109} INFO - [2022-07-14 13:19:15,827] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:19:15,828] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:19:15,840] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.023 seconds
[2022-07-14 13:19:45,893] {processor.py:163} INFO - Started process (PID=44760) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:19:45,894] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:19:45,894] {logging_mixin.py:109} INFO - [2022-07-14 13:19:45,894] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:19:45,897] {logging_mixin.py:109} INFO - [2022-07-14 13:19:45,897] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:19:45,898] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:19:45,909] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.018 seconds
[2022-07-14 13:20:16,101] {processor.py:163} INFO - Started process (PID=44812) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:20:16,102] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:20:16,102] {logging_mixin.py:109} INFO - [2022-07-14 13:20:16,102] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:20:16,106] {logging_mixin.py:109} INFO - [2022-07-14 13:20:16,105] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:20:16,106] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:20:16,117] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.018 seconds
[2022-07-14 13:20:46,909] {processor.py:163} INFO - Started process (PID=44887) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:20:46,910] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:20:46,910] {logging_mixin.py:109} INFO - [2022-07-14 13:20:46,910] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:20:46,914] {logging_mixin.py:109} INFO - [2022-07-14 13:20:46,914] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:20:46,914] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:20:46,930] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.023 seconds
[2022-07-14 13:21:17,883] {processor.py:163} INFO - Started process (PID=44955) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:21:17,884] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:21:17,884] {logging_mixin.py:109} INFO - [2022-07-14 13:21:17,884] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:21:17,887] {logging_mixin.py:109} INFO - [2022-07-14 13:21:17,887] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:21:17,887] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:21:17,901] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.019 seconds
[2022-07-14 13:21:47,936] {processor.py:163} INFO - Started process (PID=45031) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:21:47,937] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:21:47,937] {logging_mixin.py:109} INFO - [2022-07-14 13:21:47,937] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:21:47,941] {logging_mixin.py:109} INFO - [2022-07-14 13:21:47,941] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:21:47,942] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:21:47,960] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.026 seconds
[2022-07-14 13:22:18,812] {processor.py:163} INFO - Started process (PID=45105) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:22:18,813] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:22:18,814] {logging_mixin.py:109} INFO - [2022-07-14 13:22:18,814] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:22:18,819] {logging_mixin.py:109} INFO - [2022-07-14 13:22:18,818] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:22:18,819] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:22:18,831] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.021 seconds
[2022-07-14 13:22:49,683] {processor.py:163} INFO - Started process (PID=45171) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:22:49,684] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:22:49,684] {logging_mixin.py:109} INFO - [2022-07-14 13:22:49,684] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:22:49,689] {logging_mixin.py:109} INFO - [2022-07-14 13:22:49,688] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:22:49,689] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:22:49,704] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.024 seconds
[2022-07-14 13:23:20,300] {processor.py:163} INFO - Started process (PID=45245) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:23:20,303] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:23:20,304] {logging_mixin.py:109} INFO - [2022-07-14 13:23:20,304] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:23:20,309] {logging_mixin.py:109} INFO - [2022-07-14 13:23:20,308] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:23:20,309] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:23:20,322] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.024 seconds
[2022-07-14 13:23:51,022] {processor.py:163} INFO - Started process (PID=45321) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:23:51,023] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:23:51,023] {logging_mixin.py:109} INFO - [2022-07-14 13:23:51,023] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:23:51,028] {logging_mixin.py:109} INFO - [2022-07-14 13:23:51,028] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:23:51,028] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:23:51,041] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.022 seconds
[2022-07-14 13:24:21,733] {processor.py:163} INFO - Started process (PID=45388) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:24:21,734] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:24:21,734] {logging_mixin.py:109} INFO - [2022-07-14 13:24:21,734] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:24:21,739] {logging_mixin.py:109} INFO - [2022-07-14 13:24:21,738] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:24:21,739] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:24:21,753] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.023 seconds
[2022-07-14 13:24:51,846] {processor.py:163} INFO - Started process (PID=45463) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:24:51,847] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:24:51,847] {logging_mixin.py:109} INFO - [2022-07-14 13:24:51,847] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:24:51,852] {logging_mixin.py:109} INFO - [2022-07-14 13:24:51,851] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:24:51,852] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:24:51,865] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.022 seconds
[2022-07-14 13:25:22,557] {processor.py:163} INFO - Started process (PID=45538) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:25:22,558] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:25:22,558] {logging_mixin.py:109} INFO - [2022-07-14 13:25:22,558] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:25:22,562] {logging_mixin.py:109} INFO - [2022-07-14 13:25:22,561] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:25:22,562] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:25:22,576] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.021 seconds
[2022-07-14 13:25:53,321] {processor.py:163} INFO - Started process (PID=45605) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:25:53,322] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:25:53,323] {logging_mixin.py:109} INFO - [2022-07-14 13:25:53,323] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:25:53,329] {logging_mixin.py:109} INFO - [2022-07-14 13:25:53,328] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:25:53,329] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:25:53,353] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.034 seconds
[2022-07-14 13:26:24,154] {processor.py:163} INFO - Started process (PID=45682) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:26:24,158] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:26:24,159] {logging_mixin.py:109} INFO - [2022-07-14 13:26:24,159] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:26:24,164] {logging_mixin.py:109} INFO - [2022-07-14 13:26:24,163] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:26:24,164] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:26:24,181] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.029 seconds
[2022-07-14 13:26:54,939] {processor.py:163} INFO - Started process (PID=45757) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:26:54,939] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:26:54,940] {logging_mixin.py:109} INFO - [2022-07-14 13:26:54,940] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:26:54,943] {logging_mixin.py:109} INFO - [2022-07-14 13:26:54,943] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:26:54,943] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:26:54,956] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.019 seconds
[2022-07-14 13:27:25,819] {processor.py:163} INFO - Started process (PID=45823) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:27:25,819] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:27:25,820] {logging_mixin.py:109} INFO - [2022-07-14 13:27:25,820] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:27:25,823] {logging_mixin.py:109} INFO - [2022-07-14 13:27:25,822] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:27:25,823] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:27:25,836] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.019 seconds
[2022-07-14 13:27:56,596] {processor.py:163} INFO - Started process (PID=45899) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:27:56,597] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:27:56,598] {logging_mixin.py:109} INFO - [2022-07-14 13:27:56,598] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:27:56,603] {logging_mixin.py:109} INFO - [2022-07-14 13:27:56,602] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:27:56,603] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:27:56,615] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.021 seconds
[2022-07-14 13:28:27,349] {processor.py:163} INFO - Started process (PID=45975) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:28:27,350] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:28:27,351] {logging_mixin.py:109} INFO - [2022-07-14 13:28:27,351] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:28:27,355] {logging_mixin.py:109} INFO - [2022-07-14 13:28:27,355] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:28:27,356] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:28:27,371] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.024 seconds
[2022-07-14 13:28:57,475] {processor.py:163} INFO - Started process (PID=46089) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:28:57,476] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:28:57,476] {logging_mixin.py:109} INFO - [2022-07-14 13:28:57,476] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:28:57,480] {logging_mixin.py:109} INFO - [2022-07-14 13:28:57,479] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:28:57,480] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:28:57,492] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.020 seconds
[2022-07-14 13:29:28,108] {processor.py:163} INFO - Started process (PID=46167) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:29:28,109] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:29:28,110] {logging_mixin.py:109} INFO - [2022-07-14 13:29:28,110] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:29:28,115] {logging_mixin.py:109} INFO - [2022-07-14 13:29:28,114] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:29:28,115] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:29:28,127] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.021 seconds
[2022-07-14 13:29:58,219] {processor.py:163} INFO - Started process (PID=46241) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:29:58,221] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:29:58,222] {logging_mixin.py:109} INFO - [2022-07-14 13:29:58,222] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:29:58,226] {logging_mixin.py:109} INFO - [2022-07-14 13:29:58,226] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:29:58,226] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:29:58,243] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.026 seconds
[2022-07-14 13:30:28,418] {processor.py:163} INFO - Started process (PID=46325) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:30:28,419] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:30:28,419] {logging_mixin.py:109} INFO - [2022-07-14 13:30:28,419] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:30:28,423] {logging_mixin.py:109} INFO - [2022-07-14 13:30:28,423] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:30:28,423] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:30:28,436] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.022 seconds
[2022-07-14 13:30:58,573] {processor.py:163} INFO - Started process (PID=46408) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:30:58,575] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:30:58,575] {logging_mixin.py:109} INFO - [2022-07-14 13:30:58,575] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:30:58,580] {logging_mixin.py:109} INFO - [2022-07-14 13:30:58,579] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:30:58,580] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:30:58,598] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.027 seconds
[2022-07-14 13:31:28,676] {processor.py:163} INFO - Started process (PID=46482) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:31:28,677] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:31:28,678] {logging_mixin.py:109} INFO - [2022-07-14 13:31:28,678] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:31:28,683] {logging_mixin.py:109} INFO - [2022-07-14 13:31:28,682] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:31:28,683] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:31:28,699] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.028 seconds
[2022-07-14 13:31:59,015] {processor.py:163} INFO - Started process (PID=46565) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:31:59,019] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:31:59,019] {logging_mixin.py:109} INFO - [2022-07-14 13:31:59,019] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:31:59,023] {logging_mixin.py:109} INFO - [2022-07-14 13:31:59,022] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:31:59,023] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:31:59,035] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.021 seconds
[2022-07-14 13:32:29,195] {processor.py:163} INFO - Started process (PID=46639) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:32:29,199] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:32:29,199] {logging_mixin.py:109} INFO - [2022-07-14 13:32:29,199] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:32:29,203] {logging_mixin.py:109} INFO - [2022-07-14 13:32:29,202] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:32:29,203] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:32:29,217] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.024 seconds
[2022-07-14 13:32:59,550] {processor.py:163} INFO - Started process (PID=46722) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:32:59,551] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:32:59,551] {logging_mixin.py:109} INFO - [2022-07-14 13:32:59,551] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:32:59,555] {logging_mixin.py:109} INFO - [2022-07-14 13:32:59,554] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:32:59,555] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:32:59,570] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.022 seconds
[2022-07-14 13:33:29,741] {processor.py:163} INFO - Started process (PID=46809) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:33:29,742] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:33:29,742] {logging_mixin.py:109} INFO - [2022-07-14 13:33:29,742] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:33:29,748] {logging_mixin.py:109} INFO - [2022-07-14 13:33:29,747] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:33:29,748] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:33:29,770] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.032 seconds
[2022-07-14 13:34:00,047] {processor.py:163} INFO - Started process (PID=46883) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:34:00,047] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:34:00,047] {logging_mixin.py:109} INFO - [2022-07-14 13:34:00,047] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:34:00,051] {logging_mixin.py:109} INFO - [2022-07-14 13:34:00,051] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:34:00,051] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:34:00,068] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.023 seconds
[2022-07-14 13:34:30,948] {processor.py:163} INFO - Started process (PID=46966) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:34:30,949] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:34:30,950] {logging_mixin.py:109} INFO - [2022-07-14 13:34:30,950] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:34:30,955] {logging_mixin.py:109} INFO - [2022-07-14 13:34:30,954] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:34:30,955] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:34:30,967] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.021 seconds
[2022-07-14 13:35:01,189] {processor.py:163} INFO - Started process (PID=47041) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:35:01,191] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:35:01,192] {logging_mixin.py:109} INFO - [2022-07-14 13:35:01,192] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:35:01,197] {logging_mixin.py:109} INFO - [2022-07-14 13:35:01,196] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:35:01,197] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:35:01,211] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.025 seconds
[2022-07-14 13:35:31,367] {processor.py:163} INFO - Started process (PID=47124) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:35:31,368] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:35:31,368] {logging_mixin.py:109} INFO - [2022-07-14 13:35:31,368] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:35:31,371] {logging_mixin.py:109} INFO - [2022-07-14 13:35:31,371] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:35:31,372] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:35:31,385] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.020 seconds
[2022-07-14 13:36:02,317] {processor.py:163} INFO - Started process (PID=47208) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:36:02,318] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:36:02,318] {logging_mixin.py:109} INFO - [2022-07-14 13:36:02,318] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:36:02,321] {logging_mixin.py:109} INFO - [2022-07-14 13:36:02,321] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:36:02,322] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:36:02,338] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.023 seconds
[2022-07-14 13:36:32,443] {processor.py:163} INFO - Started process (PID=47282) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:36:32,443] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:36:32,444] {logging_mixin.py:109} INFO - [2022-07-14 13:36:32,444] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:36:32,447] {logging_mixin.py:109} INFO - [2022-07-14 13:36:32,447] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:36:32,448] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:36:32,460] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.020 seconds
[2022-07-14 13:37:02,782] {processor.py:163} INFO - Started process (PID=47365) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:37:02,784] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:37:02,784] {logging_mixin.py:109} INFO - [2022-07-14 13:37:02,784] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:37:02,788] {logging_mixin.py:109} INFO - [2022-07-14 13:37:02,787] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:37:02,788] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:37:02,803] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.023 seconds
[2022-07-14 13:37:33,408] {processor.py:163} INFO - Started process (PID=47439) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:37:33,409] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:37:33,410] {logging_mixin.py:109} INFO - [2022-07-14 13:37:33,410] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:37:33,415] {logging_mixin.py:109} INFO - [2022-07-14 13:37:33,414] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:37:33,415] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:37:33,431] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.025 seconds
[2022-07-14 13:38:03,690] {processor.py:163} INFO - Started process (PID=47523) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:38:03,692] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:38:03,692] {logging_mixin.py:109} INFO - [2022-07-14 13:38:03,692] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:38:03,696] {logging_mixin.py:109} INFO - [2022-07-14 13:38:03,695] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:38:03,696] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:38:03,708] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.022 seconds
[2022-07-14 13:38:33,763] {processor.py:163} INFO - Started process (PID=47608) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:38:33,763] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:38:33,764] {logging_mixin.py:109} INFO - [2022-07-14 13:38:33,764] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:38:33,767] {logging_mixin.py:109} INFO - [2022-07-14 13:38:33,767] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:38:33,767] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:38:33,786] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.025 seconds
[2022-07-14 13:39:03,932] {processor.py:163} INFO - Started process (PID=47682) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:39:03,933] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:39:03,933] {logging_mixin.py:109} INFO - [2022-07-14 13:39:03,933] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:39:03,937] {logging_mixin.py:109} INFO - [2022-07-14 13:39:03,936] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:39:03,938] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:39:03,951] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.020 seconds
[2022-07-14 13:39:34,122] {processor.py:163} INFO - Started process (PID=47765) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:39:34,123] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:39:34,123] {logging_mixin.py:109} INFO - [2022-07-14 13:39:34,123] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:39:34,129] {logging_mixin.py:109} INFO - [2022-07-14 13:39:34,129] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:39:34,130] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:39:34,147] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.027 seconds
[2022-07-14 13:40:04,508] {processor.py:163} INFO - Started process (PID=47839) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:40:04,509] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:40:04,509] {logging_mixin.py:109} INFO - [2022-07-14 13:40:04,509] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:40:04,513] {logging_mixin.py:109} INFO - [2022-07-14 13:40:04,513] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:40:04,514] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:40:04,526] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.022 seconds
[2022-07-14 13:40:34,671] {processor.py:163} INFO - Started process (PID=47922) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:40:34,672] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:40:34,673] {logging_mixin.py:109} INFO - [2022-07-14 13:40:34,673] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:40:34,679] {logging_mixin.py:109} INFO - [2022-07-14 13:40:34,678] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:40:34,679] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:40:34,695] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.026 seconds
[2022-07-14 13:41:04,963] {processor.py:163} INFO - Started process (PID=48007) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:41:04,964] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:41:04,965] {logging_mixin.py:109} INFO - [2022-07-14 13:41:04,965] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:41:04,971] {logging_mixin.py:109} INFO - [2022-07-14 13:41:04,970] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:41:04,971] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:41:04,993] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.033 seconds
[2022-07-14 13:41:35,234] {processor.py:163} INFO - Started process (PID=48082) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:41:35,235] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:41:35,235] {logging_mixin.py:109} INFO - [2022-07-14 13:41:35,235] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:41:35,238] {logging_mixin.py:109} INFO - [2022-07-14 13:41:35,238] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:41:35,239] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:41:35,251] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.019 seconds
[2022-07-14 13:42:05,642] {processor.py:163} INFO - Started process (PID=48167) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:42:05,643] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:42:05,643] {logging_mixin.py:109} INFO - [2022-07-14 13:42:05,643] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:42:05,648] {logging_mixin.py:109} INFO - [2022-07-14 13:42:05,647] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:42:05,648] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:42:05,664] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.024 seconds
[2022-07-14 13:42:36,139] {processor.py:163} INFO - Started process (PID=48241) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:42:36,140] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:42:36,140] {logging_mixin.py:109} INFO - [2022-07-14 13:42:36,140] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:42:36,144] {logging_mixin.py:109} INFO - [2022-07-14 13:42:36,144] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:42:36,144] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:42:36,159] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.023 seconds
[2022-07-14 13:43:06,286] {processor.py:163} INFO - Started process (PID=48325) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:43:06,287] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:43:06,287] {logging_mixin.py:109} INFO - [2022-07-14 13:43:06,287] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:43:06,291] {logging_mixin.py:109} INFO - [2022-07-14 13:43:06,290] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:43:06,292] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:43:06,311] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.027 seconds
[2022-07-14 13:43:36,572] {processor.py:163} INFO - Started process (PID=48400) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:43:36,573] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:43:36,573] {logging_mixin.py:109} INFO - [2022-07-14 13:43:36,573] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:43:36,578] {logging_mixin.py:109} INFO - [2022-07-14 13:43:36,577] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:43:36,578] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:43:36,591] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.020 seconds
[2022-07-14 13:44:06,994] {processor.py:163} INFO - Started process (PID=48484) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:44:06,995] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:44:06,995] {logging_mixin.py:109} INFO - [2022-07-14 13:44:06,995] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:44:07,000] {logging_mixin.py:109} INFO - [2022-07-14 13:44:06,999] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:44:07,000] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:44:07,012] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.020 seconds
[2022-07-14 13:44:37,056] {processor.py:163} INFO - Started process (PID=48569) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:44:37,057] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:44:37,057] {logging_mixin.py:109} INFO - [2022-07-14 13:44:37,057] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:44:37,061] {logging_mixin.py:109} INFO - [2022-07-14 13:44:37,060] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:44:37,061] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:44:37,078] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.025 seconds
[2022-07-14 13:45:07,342] {processor.py:163} INFO - Started process (PID=48643) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:45:07,343] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:45:07,343] {logging_mixin.py:109} INFO - [2022-07-14 13:45:07,343] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:45:07,347] {logging_mixin.py:109} INFO - [2022-07-14 13:45:07,346] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:45:07,347] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:45:07,364] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.023 seconds
[2022-07-14 13:45:37,870] {processor.py:163} INFO - Started process (PID=48726) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:45:37,871] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:45:37,871] {logging_mixin.py:109} INFO - [2022-07-14 13:45:37,871] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:45:37,876] {logging_mixin.py:109} INFO - [2022-07-14 13:45:37,875] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:45:37,876] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:45:37,889] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.021 seconds
[2022-07-14 13:46:07,994] {processor.py:163} INFO - Started process (PID=48802) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:46:07,995] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:46:07,995] {logging_mixin.py:109} INFO - [2022-07-14 13:46:07,995] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:46:07,999] {logging_mixin.py:109} INFO - [2022-07-14 13:46:07,999] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:46:08,000] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:46:08,012] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.020 seconds
[2022-07-14 13:46:38,185] {processor.py:163} INFO - Started process (PID=48885) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:46:38,186] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:46:38,186] {logging_mixin.py:109} INFO - [2022-07-14 13:46:38,186] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:46:38,190] {logging_mixin.py:109} INFO - [2022-07-14 13:46:38,189] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:46:38,190] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:46:38,203] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.019 seconds
[2022-07-14 13:47:08,397] {processor.py:163} INFO - Started process (PID=48968) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:47:08,398] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:47:08,398] {logging_mixin.py:109} INFO - [2022-07-14 13:47:08,398] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:47:08,404] {logging_mixin.py:109} INFO - [2022-07-14 13:47:08,403] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:47:08,404] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:47:08,423] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.029 seconds
[2022-07-14 13:47:38,744] {processor.py:163} INFO - Started process (PID=49042) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:47:38,745] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:47:38,746] {logging_mixin.py:109} INFO - [2022-07-14 13:47:38,746] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:47:38,750] {logging_mixin.py:109} INFO - [2022-07-14 13:47:38,750] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:47:38,751] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:47:38,766] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.024 seconds
[2022-07-14 13:48:09,016] {processor.py:163} INFO - Started process (PID=49130) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:48:09,016] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:48:09,017] {logging_mixin.py:109} INFO - [2022-07-14 13:48:09,017] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:48:09,020] {logging_mixin.py:109} INFO - [2022-07-14 13:48:09,020] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:48:09,020] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:48:09,034] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.019 seconds
[2022-07-14 13:48:39,302] {processor.py:163} INFO - Started process (PID=49204) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:48:39,302] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:48:39,303] {logging_mixin.py:109} INFO - [2022-07-14 13:48:39,303] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:48:39,308] {logging_mixin.py:109} INFO - [2022-07-14 13:48:39,307] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:48:39,308] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:48:39,321] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.022 seconds
[2022-07-14 13:49:09,481] {processor.py:163} INFO - Started process (PID=49287) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:49:09,481] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:49:09,482] {logging_mixin.py:109} INFO - [2022-07-14 13:49:09,482] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:49:09,487] {logging_mixin.py:109} INFO - [2022-07-14 13:49:09,486] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:49:09,487] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:49:09,504] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.026 seconds
[2022-07-14 13:49:39,581] {processor.py:163} INFO - Started process (PID=49360) to work on /opt/airflow/dags/firsttest.py
[2022-07-14 13:49:39,583] {processor.py:642} INFO - Processing file /opt/airflow/dags/firsttest.py for tasks to queue
[2022-07-14 13:49:39,583] {logging_mixin.py:109} INFO - [2022-07-14 13:49:39,583] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/firsttest.py
[2022-07-14 13:49:39,587] {logging_mixin.py:109} INFO - [2022-07-14 13:49:39,586] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/firsttest.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/firsttest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-14 13:49:39,587] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/firsttest.py
[2022-07-14 13:49:39,599] {processor.py:171} INFO - Processing /opt/airflow/dags/firsttest.py took 0.020 seconds
