[2022-07-14 13:18:45,670] {processor.py:163} INFO - Started process (PID=44620) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:18:45,671] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:18:45,671] {logging_mixin.py:109} INFO - [2022-07-14 13:18:45,671] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:18:45,676] {logging_mixin.py:109} INFO - [2022-07-14 13:18:45,675] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:18:45,676] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:18:45,689] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.021 seconds
[2022-07-14 13:19:15,851] {processor.py:163} INFO - Started process (PID=44695) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:19:15,851] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:19:15,852] {logging_mixin.py:109} INFO - [2022-07-14 13:19:15,852] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:19:15,857] {logging_mixin.py:109} INFO - [2022-07-14 13:19:15,856] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:19:15,857] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:19:15,868] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.019 seconds
[2022-07-14 13:19:45,925] {processor.py:163} INFO - Started process (PID=44761) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:19:45,925] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:19:45,926] {logging_mixin.py:109} INFO - [2022-07-14 13:19:45,926] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:19:45,930] {logging_mixin.py:109} INFO - [2022-07-14 13:19:45,929] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:19:45,930] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:19:45,947] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.025 seconds
[2022-07-14 13:20:16,128] {processor.py:163} INFO - Started process (PID=44813) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:20:16,129] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:20:16,129] {logging_mixin.py:109} INFO - [2022-07-14 13:20:16,129] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:20:16,134] {logging_mixin.py:109} INFO - [2022-07-14 13:20:16,133] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:20:16,134] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:20:16,146] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.020 seconds
[2022-07-14 13:20:46,944] {processor.py:163} INFO - Started process (PID=44888) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:20:46,945] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:20:46,945] {logging_mixin.py:109} INFO - [2022-07-14 13:20:46,945] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:20:46,950] {logging_mixin.py:109} INFO - [2022-07-14 13:20:46,949] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:20:46,950] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:20:46,962] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.021 seconds
[2022-07-14 13:21:17,913] {processor.py:163} INFO - Started process (PID=44956) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:21:17,914] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:21:17,914] {logging_mixin.py:109} INFO - [2022-07-14 13:21:17,914] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:21:17,919] {logging_mixin.py:109} INFO - [2022-07-14 13:21:17,918] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:21:17,919] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:21:17,932] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.021 seconds
[2022-07-14 13:21:47,973] {processor.py:163} INFO - Started process (PID=45032) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:21:47,974] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:21:47,974] {logging_mixin.py:109} INFO - [2022-07-14 13:21:47,974] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:21:47,980] {logging_mixin.py:109} INFO - [2022-07-14 13:21:47,979] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:21:47,980] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:21:47,993] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.022 seconds
[2022-07-14 13:22:18,842] {processor.py:163} INFO - Started process (PID=45106) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:22:18,842] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:22:18,843] {logging_mixin.py:109} INFO - [2022-07-14 13:22:18,843] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:22:18,847] {logging_mixin.py:109} INFO - [2022-07-14 13:22:18,846] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:22:18,847] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:22:18,860] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.021 seconds
[2022-07-14 13:22:49,719] {processor.py:163} INFO - Started process (PID=45172) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:22:49,719] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:22:49,720] {logging_mixin.py:109} INFO - [2022-07-14 13:22:49,720] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:22:49,724] {logging_mixin.py:109} INFO - [2022-07-14 13:22:49,724] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:22:49,725] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:22:49,736] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.019 seconds
[2022-07-14 13:23:20,334] {processor.py:163} INFO - Started process (PID=45246) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:23:20,335] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:23:20,335] {logging_mixin.py:109} INFO - [2022-07-14 13:23:20,335] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:23:20,340] {logging_mixin.py:109} INFO - [2022-07-14 13:23:20,340] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:23:20,341] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:23:20,353] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.022 seconds
[2022-07-14 13:23:51,054] {processor.py:163} INFO - Started process (PID=45322) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:23:51,055] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:23:51,055] {logging_mixin.py:109} INFO - [2022-07-14 13:23:51,055] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:23:51,060] {logging_mixin.py:109} INFO - [2022-07-14 13:23:51,059] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:23:51,060] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:23:51,071] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.019 seconds
[2022-07-14 13:24:21,764] {processor.py:163} INFO - Started process (PID=45389) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:24:21,765] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:24:21,765] {logging_mixin.py:109} INFO - [2022-07-14 13:24:21,765] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:24:21,770] {logging_mixin.py:109} INFO - [2022-07-14 13:24:21,769] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:24:21,770] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:24:21,781] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.019 seconds
[2022-07-14 13:24:51,877] {processor.py:163} INFO - Started process (PID=45464) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:24:51,878] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:24:51,878] {logging_mixin.py:109} INFO - [2022-07-14 13:24:51,878] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:24:51,882] {logging_mixin.py:109} INFO - [2022-07-14 13:24:51,881] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:24:51,882] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:24:51,893] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.018 seconds
[2022-07-14 13:25:22,590] {processor.py:163} INFO - Started process (PID=45539) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:25:22,591] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:25:22,591] {logging_mixin.py:109} INFO - [2022-07-14 13:25:22,591] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:25:22,596] {logging_mixin.py:109} INFO - [2022-07-14 13:25:22,595] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:25:22,596] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:25:22,607] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.019 seconds
[2022-07-14 13:25:53,368] {processor.py:163} INFO - Started process (PID=45606) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:25:53,368] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:25:53,369] {logging_mixin.py:109} INFO - [2022-07-14 13:25:53,369] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:25:53,374] {logging_mixin.py:109} INFO - [2022-07-14 13:25:53,373] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:25:53,374] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:25:53,391] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.025 seconds
[2022-07-14 13:26:24,201] {processor.py:163} INFO - Started process (PID=45683) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:26:24,202] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:26:24,202] {logging_mixin.py:109} INFO - [2022-07-14 13:26:24,202] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:26:24,209] {logging_mixin.py:109} INFO - [2022-07-14 13:26:24,207] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:26:24,209] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:26:24,222] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.024 seconds
[2022-07-14 13:26:54,971] {processor.py:163} INFO - Started process (PID=45758) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:26:54,972] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:26:54,973] {logging_mixin.py:109} INFO - [2022-07-14 13:26:54,972] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:26:54,977] {logging_mixin.py:109} INFO - [2022-07-14 13:26:54,976] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:26:54,977] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:26:54,989] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.020 seconds
[2022-07-14 13:27:25,847] {processor.py:163} INFO - Started process (PID=45824) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:27:25,848] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:27:25,848] {logging_mixin.py:109} INFO - [2022-07-14 13:27:25,848] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:27:25,852] {logging_mixin.py:109} INFO - [2022-07-14 13:27:25,851] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:27:25,852] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:27:25,863] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.018 seconds
[2022-07-14 13:27:56,626] {processor.py:163} INFO - Started process (PID=45900) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:27:56,627] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:27:56,627] {logging_mixin.py:109} INFO - [2022-07-14 13:27:56,627] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:27:56,632] {logging_mixin.py:109} INFO - [2022-07-14 13:27:56,632] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:27:56,632] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:27:56,644] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.020 seconds
[2022-07-14 13:28:27,383] {processor.py:163} INFO - Started process (PID=45976) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:28:27,383] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:28:27,384] {logging_mixin.py:109} INFO - [2022-07-14 13:28:27,384] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:28:27,388] {logging_mixin.py:109} INFO - [2022-07-14 13:28:27,387] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:28:27,388] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:28:27,399] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.018 seconds
[2022-07-14 13:28:57,496] {processor.py:163} INFO - Started process (PID=46090) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:28:57,497] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:28:57,497] {logging_mixin.py:109} INFO - [2022-07-14 13:28:57,497] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:28:57,501] {logging_mixin.py:109} INFO - [2022-07-14 13:28:57,501] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:28:57,501] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:28:57,512] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.018 seconds
[2022-07-14 13:29:28,138] {processor.py:163} INFO - Started process (PID=46168) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:29:28,138] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:29:28,139] {logging_mixin.py:109} INFO - [2022-07-14 13:29:28,139] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:29:28,143] {logging_mixin.py:109} INFO - [2022-07-14 13:29:28,142] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:29:28,143] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:29:28,157] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.022 seconds
[2022-07-14 13:29:58,256] {processor.py:163} INFO - Started process (PID=46242) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:29:58,257] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:29:58,257] {logging_mixin.py:109} INFO - [2022-07-14 13:29:58,257] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:29:58,261] {logging_mixin.py:109} INFO - [2022-07-14 13:29:58,260] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:29:58,261] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:29:58,273] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.019 seconds
[2022-07-14 13:30:28,447] {processor.py:163} INFO - Started process (PID=46326) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:30:28,448] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:30:28,448] {logging_mixin.py:109} INFO - [2022-07-14 13:30:28,448] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:30:28,453] {logging_mixin.py:109} INFO - [2022-07-14 13:30:28,452] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:30:28,453] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:30:28,467] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.022 seconds
[2022-07-14 13:30:58,612] {processor.py:163} INFO - Started process (PID=46409) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:30:58,613] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:30:58,613] {logging_mixin.py:109} INFO - [2022-07-14 13:30:58,613] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:30:58,618] {logging_mixin.py:109} INFO - [2022-07-14 13:30:58,617] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:30:58,618] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:30:58,637] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.027 seconds
[2022-07-14 13:31:28,711] {processor.py:163} INFO - Started process (PID=46483) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:31:28,712] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:31:28,712] {logging_mixin.py:109} INFO - [2022-07-14 13:31:28,712] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:31:28,717] {logging_mixin.py:109} INFO - [2022-07-14 13:31:28,716] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:31:28,717] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:31:28,729] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.020 seconds
[2022-07-14 13:31:59,047] {processor.py:163} INFO - Started process (PID=46566) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:31:59,047] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:31:59,048] {logging_mixin.py:109} INFO - [2022-07-14 13:31:59,048] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:31:59,053] {logging_mixin.py:109} INFO - [2022-07-14 13:31:59,052] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:31:59,054] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:31:59,065] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.020 seconds
[2022-07-14 13:32:29,231] {processor.py:163} INFO - Started process (PID=46640) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:32:29,232] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:32:29,232] {logging_mixin.py:109} INFO - [2022-07-14 13:32:29,232] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:32:29,238] {logging_mixin.py:109} INFO - [2022-07-14 13:32:29,237] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:32:29,238] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:32:29,250] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.021 seconds
[2022-07-14 13:32:59,585] {processor.py:163} INFO - Started process (PID=46723) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:32:59,587] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:32:59,587] {logging_mixin.py:109} INFO - [2022-07-14 13:32:59,587] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:32:59,594] {logging_mixin.py:109} INFO - [2022-07-14 13:32:59,592] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:32:59,594] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:32:59,607] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.025 seconds
[2022-07-14 13:33:29,784] {processor.py:163} INFO - Started process (PID=46810) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:33:29,785] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:33:29,785] {logging_mixin.py:109} INFO - [2022-07-14 13:33:29,785] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:33:29,790] {logging_mixin.py:109} INFO - [2022-07-14 13:33:29,789] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:33:29,790] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:33:29,807] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.025 seconds
[2022-07-14 13:34:00,080] {processor.py:163} INFO - Started process (PID=46884) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:34:00,081] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:34:00,081] {logging_mixin.py:109} INFO - [2022-07-14 13:34:00,081] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:34:00,085] {logging_mixin.py:109} INFO - [2022-07-14 13:34:00,085] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:34:00,085] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:34:00,097] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.018 seconds
[2022-07-14 13:34:30,981] {processor.py:163} INFO - Started process (PID=46967) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:34:30,981] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:34:30,982] {logging_mixin.py:109} INFO - [2022-07-14 13:34:30,982] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:34:30,986] {logging_mixin.py:109} INFO - [2022-07-14 13:34:30,985] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:34:30,986] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:34:30,998] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.019 seconds
[2022-07-14 13:35:01,231] {processor.py:163} INFO - Started process (PID=47042) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:35:01,232] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:35:01,232] {logging_mixin.py:109} INFO - [2022-07-14 13:35:01,232] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:35:01,238] {logging_mixin.py:109} INFO - [2022-07-14 13:35:01,237] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:35:01,238] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:35:01,254] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.025 seconds
[2022-07-14 13:35:31,399] {processor.py:163} INFO - Started process (PID=47125) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:35:31,400] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:35:31,400] {logging_mixin.py:109} INFO - [2022-07-14 13:35:31,400] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:35:31,405] {logging_mixin.py:109} INFO - [2022-07-14 13:35:31,404] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:35:31,405] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:35:31,417] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.020 seconds
[2022-07-14 13:36:02,355] {processor.py:163} INFO - Started process (PID=47209) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:36:02,356] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:36:02,356] {logging_mixin.py:109} INFO - [2022-07-14 13:36:02,356] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:36:02,363] {logging_mixin.py:109} INFO - [2022-07-14 13:36:02,361] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:36:02,364] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:36:02,384] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.032 seconds
[2022-07-14 13:36:32,472] {processor.py:163} INFO - Started process (PID=47283) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:36:32,473] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:36:32,473] {logging_mixin.py:109} INFO - [2022-07-14 13:36:32,473] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:36:32,477] {logging_mixin.py:109} INFO - [2022-07-14 13:36:32,477] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:36:32,477] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:36:32,488] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.019 seconds
[2022-07-14 13:37:02,833] {processor.py:163} INFO - Started process (PID=47366) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:37:02,834] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:37:02,835] {logging_mixin.py:109} INFO - [2022-07-14 13:37:02,834] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:37:02,839] {logging_mixin.py:109} INFO - [2022-07-14 13:37:02,839] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:37:02,840] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:37:02,861] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.032 seconds
[2022-07-14 13:37:33,448] {processor.py:163} INFO - Started process (PID=47440) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:37:33,449] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:37:33,450] {logging_mixin.py:109} INFO - [2022-07-14 13:37:33,449] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:37:33,457] {logging_mixin.py:109} INFO - [2022-07-14 13:37:33,456] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:37:33,457] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:37:33,474] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.030 seconds
[2022-07-14 13:38:03,720] {processor.py:163} INFO - Started process (PID=47524) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:38:03,721] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:38:03,721] {logging_mixin.py:109} INFO - [2022-07-14 13:38:03,721] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:38:03,726] {logging_mixin.py:109} INFO - [2022-07-14 13:38:03,725] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:38:03,726] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:38:03,737] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.018 seconds
[2022-07-14 13:38:33,805] {processor.py:163} INFO - Started process (PID=47609) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:38:33,807] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:38:33,807] {logging_mixin.py:109} INFO - [2022-07-14 13:38:33,807] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:38:33,814] {logging_mixin.py:109} INFO - [2022-07-14 13:38:33,813] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:38:33,814] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:38:33,834] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.035 seconds
[2022-07-14 13:39:03,967] {processor.py:163} INFO - Started process (PID=47683) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:39:03,968] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:39:03,968] {logging_mixin.py:109} INFO - [2022-07-14 13:39:03,968] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:39:03,975] {logging_mixin.py:109} INFO - [2022-07-14 13:39:03,974] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:39:03,975] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:39:03,987] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.022 seconds
[2022-07-14 13:39:34,161] {processor.py:163} INFO - Started process (PID=47766) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:39:34,161] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:39:34,162] {logging_mixin.py:109} INFO - [2022-07-14 13:39:34,162] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:39:34,167] {logging_mixin.py:109} INFO - [2022-07-14 13:39:34,166] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:39:34,167] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:39:34,179] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.021 seconds
[2022-07-14 13:40:04,540] {processor.py:163} INFO - Started process (PID=47840) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:40:04,540] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:40:04,541] {logging_mixin.py:109} INFO - [2022-07-14 13:40:04,541] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:40:04,545] {logging_mixin.py:109} INFO - [2022-07-14 13:40:04,544] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:40:04,545] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:40:04,556] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.018 seconds
[2022-07-14 13:40:34,708] {processor.py:163} INFO - Started process (PID=47923) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:40:34,709] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:40:34,709] {logging_mixin.py:109} INFO - [2022-07-14 13:40:34,709] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:40:34,714] {logging_mixin.py:109} INFO - [2022-07-14 13:40:34,713] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:40:34,714] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:40:34,728] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.022 seconds
[2022-07-14 13:41:05,009] {processor.py:163} INFO - Started process (PID=48008) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:41:05,010] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:41:05,010] {logging_mixin.py:109} INFO - [2022-07-14 13:41:05,010] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:41:05,014] {logging_mixin.py:109} INFO - [2022-07-14 13:41:05,013] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:41:05,014] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:41:05,027] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.021 seconds
[2022-07-14 13:41:35,262] {processor.py:163} INFO - Started process (PID=48083) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:41:35,263] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:41:35,263] {logging_mixin.py:109} INFO - [2022-07-14 13:41:35,263] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:41:35,268] {logging_mixin.py:109} INFO - [2022-07-14 13:41:35,267] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:41:35,268] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:41:35,280] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.020 seconds
[2022-07-14 13:42:05,678] {processor.py:163} INFO - Started process (PID=48168) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:42:05,679] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:42:05,679] {logging_mixin.py:109} INFO - [2022-07-14 13:42:05,679] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:42:05,684] {logging_mixin.py:109} INFO - [2022-07-14 13:42:05,683] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:42:05,684] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:42:05,697] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.020 seconds
[2022-07-14 13:42:36,171] {processor.py:163} INFO - Started process (PID=48242) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:42:36,172] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:42:36,172] {logging_mixin.py:109} INFO - [2022-07-14 13:42:36,172] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:42:36,177] {logging_mixin.py:109} INFO - [2022-07-14 13:42:36,176] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:42:36,177] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:42:36,190] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.020 seconds
[2022-07-14 13:43:06,325] {processor.py:163} INFO - Started process (PID=48326) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:43:06,326] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:43:06,326] {logging_mixin.py:109} INFO - [2022-07-14 13:43:06,326] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:43:06,331] {logging_mixin.py:109} INFO - [2022-07-14 13:43:06,330] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:43:06,331] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:43:06,342] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.018 seconds
[2022-07-14 13:43:36,603] {processor.py:163} INFO - Started process (PID=48401) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:43:36,604] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:43:36,604] {logging_mixin.py:109} INFO - [2022-07-14 13:43:36,604] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:43:36,609] {logging_mixin.py:109} INFO - [2022-07-14 13:43:36,608] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:43:36,609] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:43:36,621] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.020 seconds
[2022-07-14 13:44:07,027] {processor.py:163} INFO - Started process (PID=48485) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:44:07,028] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:44:07,028] {logging_mixin.py:109} INFO - [2022-07-14 13:44:07,028] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:44:07,032] {logging_mixin.py:109} INFO - [2022-07-14 13:44:07,032] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:44:07,033] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:44:07,043] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.018 seconds
[2022-07-14 13:44:37,093] {processor.py:163} INFO - Started process (PID=48570) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:44:37,094] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:44:37,094] {logging_mixin.py:109} INFO - [2022-07-14 13:44:37,094] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:44:37,099] {logging_mixin.py:109} INFO - [2022-07-14 13:44:37,098] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:44:37,099] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:44:37,113] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.022 seconds
[2022-07-14 13:45:07,377] {processor.py:163} INFO - Started process (PID=48644) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:45:07,377] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:45:07,378] {logging_mixin.py:109} INFO - [2022-07-14 13:45:07,378] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:45:07,383] {logging_mixin.py:109} INFO - [2022-07-14 13:45:07,382] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:45:07,383] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:45:07,394] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.019 seconds
[2022-07-14 13:45:37,901] {processor.py:163} INFO - Started process (PID=48727) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:45:37,902] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:45:37,902] {logging_mixin.py:109} INFO - [2022-07-14 13:45:37,902] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:45:37,907] {logging_mixin.py:109} INFO - [2022-07-14 13:45:37,906] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:45:37,907] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:45:37,919] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.019 seconds
[2022-07-14 13:46:08,024] {processor.py:163} INFO - Started process (PID=48803) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:46:08,024] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:46:08,025] {logging_mixin.py:109} INFO - [2022-07-14 13:46:08,025] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:46:08,030] {logging_mixin.py:109} INFO - [2022-07-14 13:46:08,029] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:46:08,030] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:46:08,044] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.022 seconds
[2022-07-14 13:46:38,241] {processor.py:163} INFO - Started process (PID=48886) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:46:38,242] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:46:38,242] {logging_mixin.py:109} INFO - [2022-07-14 13:46:38,242] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:46:38,249] {logging_mixin.py:109} INFO - [2022-07-14 13:46:38,248] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:46:38,249] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:46:38,262] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.023 seconds
[2022-07-14 13:47:08,443] {processor.py:163} INFO - Started process (PID=48969) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:47:08,444] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:47:08,446] {logging_mixin.py:109} INFO - [2022-07-14 13:47:08,445] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:47:08,453] {logging_mixin.py:109} INFO - [2022-07-14 13:47:08,452] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:47:08,454] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:47:08,472] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.032 seconds
[2022-07-14 13:47:38,777] {processor.py:163} INFO - Started process (PID=49043) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:47:38,778] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:47:38,779] {logging_mixin.py:109} INFO - [2022-07-14 13:47:38,778] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:47:38,784] {logging_mixin.py:109} INFO - [2022-07-14 13:47:38,783] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:47:38,784] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:47:38,796] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.021 seconds
[2022-07-14 13:48:09,046] {processor.py:163} INFO - Started process (PID=49131) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:48:09,046] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:48:09,047] {logging_mixin.py:109} INFO - [2022-07-14 13:48:09,047] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:48:09,051] {logging_mixin.py:109} INFO - [2022-07-14 13:48:09,051] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:48:09,051] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:48:09,065] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.022 seconds
[2022-07-14 13:48:39,335] {processor.py:163} INFO - Started process (PID=49205) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:48:39,336] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:48:39,336] {logging_mixin.py:109} INFO - [2022-07-14 13:48:39,336] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:48:39,341] {logging_mixin.py:109} INFO - [2022-07-14 13:48:39,341] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:48:39,342] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:48:39,356] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.023 seconds
[2022-07-14 13:49:09,518] {processor.py:163} INFO - Started process (PID=49288) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:49:09,519] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:49:09,520] {logging_mixin.py:109} INFO - [2022-07-14 13:49:09,520] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:49:09,525] {logging_mixin.py:109} INFO - [2022-07-14 13:49:09,524] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:49:09,525] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:49:09,545] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.029 seconds
[2022-07-14 13:49:39,610] {processor.py:163} INFO - Started process (PID=49361) to work on /opt/airflow/dags/static_sum.py
[2022-07-14 13:49:39,611] {processor.py:642} INFO - Processing file /opt/airflow/dags/static_sum.py for tasks to queue
[2022-07-14 13:49:39,611] {logging_mixin.py:109} INFO - [2022-07-14 13:49:39,611] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/static_sum.py
[2022-07-14 13:49:39,617] {logging_mixin.py:109} INFO - [2022-07-14 13:49:39,615] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/static_sum.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/static_sum.py", line 15, in <module>
    hello = HelloOperator(task_id="demo",a=20,b=20)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_args'
[2022-07-14 13:49:39,617] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/static_sum.py
[2022-07-14 13:49:39,630] {processor.py:171} INFO - Processing /opt/airflow/dags/static_sum.py took 0.022 seconds
