[2022-07-13 05:08:59,404] {processor.py:163} INFO - Started process (PID=35) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:08:59,404] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:08:59,405] {logging_mixin.py:109} INFO - [2022-07-13 05:08:59,405] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:08:59,406] {logging_mixin.py:109} INFO - [2022-07-13 05:08:59,406] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:08:59,406] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:08:59,419] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.018 seconds
[2022-07-13 05:09:29,792] {processor.py:163} INFO - Started process (PID=107) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:09:29,792] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:09:29,793] {logging_mixin.py:109} INFO - [2022-07-13 05:09:29,793] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:09:29,794] {logging_mixin.py:109} INFO - [2022-07-13 05:09:29,794] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:09:29,794] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:09:29,806] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:10:00,853] {processor.py:163} INFO - Started process (PID=177) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:10:00,854] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:10:00,854] {logging_mixin.py:109} INFO - [2022-07-13 05:10:00,854] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:10:00,855] {logging_mixin.py:109} INFO - [2022-07-13 05:10:00,855] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:10:00,855] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:10:00,867] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:10:30,888] {processor.py:163} INFO - Started process (PID=241) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:10:30,889] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:10:30,889] {logging_mixin.py:109} INFO - [2022-07-13 05:10:30,889] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:10:30,891] {logging_mixin.py:109} INFO - [2022-07-13 05:10:30,890] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:10:30,891] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:10:30,904] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.017 seconds
[2022-07-13 05:11:01,406] {processor.py:163} INFO - Started process (PID=312) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:11:01,406] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:11:01,407] {logging_mixin.py:109} INFO - [2022-07-13 05:11:01,407] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:11:01,408] {logging_mixin.py:109} INFO - [2022-07-13 05:11:01,408] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:11:01,408] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:11:01,420] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:11:32,363] {processor.py:163} INFO - Started process (PID=375) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:11:32,363] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:11:32,364] {logging_mixin.py:109} INFO - [2022-07-13 05:11:32,364] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:11:32,365] {logging_mixin.py:109} INFO - [2022-07-13 05:11:32,364] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:11:32,365] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:11:32,376] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:12:03,166] {processor.py:163} INFO - Started process (PID=448) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:12:03,166] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:12:03,166] {logging_mixin.py:109} INFO - [2022-07-13 05:12:03,166] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:12:03,168] {logging_mixin.py:109} INFO - [2022-07-13 05:12:03,167] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:12:03,168] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:12:03,180] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:12:34,118] {processor.py:163} INFO - Started process (PID=519) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:12:34,119] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:12:34,119] {logging_mixin.py:109} INFO - [2022-07-13 05:12:34,119] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:12:34,120] {logging_mixin.py:109} INFO - [2022-07-13 05:12:34,120] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:12:34,121] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:12:34,135] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.018 seconds
[2022-07-13 05:13:05,003] {processor.py:163} INFO - Started process (PID=591) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:13:05,004] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:13:05,004] {logging_mixin.py:109} INFO - [2022-07-13 05:13:05,004] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:13:05,006] {logging_mixin.py:109} INFO - [2022-07-13 05:13:05,005] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:13:05,006] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:13:05,021] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.019 seconds
[2022-07-13 05:13:35,766] {processor.py:163} INFO - Started process (PID=654) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:13:35,766] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:13:35,767] {logging_mixin.py:109} INFO - [2022-07-13 05:13:35,767] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:13:35,768] {logging_mixin.py:109} INFO - [2022-07-13 05:13:35,768] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:13:35,769] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:13:35,785] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.021 seconds
[2022-07-13 05:14:06,192] {processor.py:163} INFO - Started process (PID=726) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:14:06,192] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:14:06,193] {logging_mixin.py:109} INFO - [2022-07-13 05:14:06,193] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:14:06,194] {logging_mixin.py:109} INFO - [2022-07-13 05:14:06,194] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:14:06,194] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:14:06,206] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:14:36,247] {processor.py:163} INFO - Started process (PID=788) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:14:36,249] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:14:36,250] {logging_mixin.py:109} INFO - [2022-07-13 05:14:36,250] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:14:36,252] {logging_mixin.py:109} INFO - [2022-07-13 05:14:36,251] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:14:36,252] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:14:36,276] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.032 seconds
[2022-07-13 05:15:06,613] {processor.py:163} INFO - Started process (PID=861) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:15:06,614] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:15:06,614] {logging_mixin.py:109} INFO - [2022-07-13 05:15:06,614] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:15:06,616] {logging_mixin.py:109} INFO - [2022-07-13 05:15:06,615] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:15:06,616] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:15:06,626] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:15:36,668] {processor.py:163} INFO - Started process (PID=932) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:15:36,669] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:15:36,669] {logging_mixin.py:109} INFO - [2022-07-13 05:15:36,669] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:15:36,670] {logging_mixin.py:109} INFO - [2022-07-13 05:15:36,670] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:15:36,670] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:15:36,681] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:16:07,456] {processor.py:163} INFO - Started process (PID=994) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:16:07,456] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:16:07,457] {logging_mixin.py:109} INFO - [2022-07-13 05:16:07,457] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:16:07,458] {logging_mixin.py:109} INFO - [2022-07-13 05:16:07,458] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:16:07,458] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:16:07,471] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.017 seconds
[2022-07-13 05:16:38,224] {processor.py:163} INFO - Started process (PID=1066) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:16:38,225] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:16:38,225] {logging_mixin.py:109} INFO - [2022-07-13 05:16:38,225] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:16:38,226] {logging_mixin.py:109} INFO - [2022-07-13 05:16:38,226] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:16:38,226] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:16:38,237] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:17:08,288] {processor.py:163} INFO - Started process (PID=1137) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:17:08,288] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:17:08,289] {logging_mixin.py:109} INFO - [2022-07-13 05:17:08,289] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:17:08,290] {logging_mixin.py:109} INFO - [2022-07-13 05:17:08,290] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:17:08,290] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:17:08,303] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.017 seconds
[2022-07-13 05:17:39,199] {processor.py:163} INFO - Started process (PID=1199) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:17:39,200] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:17:39,200] {logging_mixin.py:109} INFO - [2022-07-13 05:17:39,200] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:17:39,201] {logging_mixin.py:109} INFO - [2022-07-13 05:17:39,201] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:17:39,201] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:17:39,213] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:18:10,114] {processor.py:163} INFO - Started process (PID=1271) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:18:10,115] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:18:10,115] {logging_mixin.py:109} INFO - [2022-07-13 05:18:10,115] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:18:10,116] {logging_mixin.py:109} INFO - [2022-07-13 05:18:10,116] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:18:10,116] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:18:10,127] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:18:40,257] {processor.py:163} INFO - Started process (PID=1342) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:18:40,257] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:18:40,258] {logging_mixin.py:109} INFO - [2022-07-13 05:18:40,258] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:18:40,259] {logging_mixin.py:109} INFO - [2022-07-13 05:18:40,259] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:18:40,259] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:18:40,273] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.018 seconds
[2022-07-13 05:19:11,285] {processor.py:163} INFO - Started process (PID=1404) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:19:11,286] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:19:11,286] {logging_mixin.py:109} INFO - [2022-07-13 05:19:11,286] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:19:11,287] {logging_mixin.py:109} INFO - [2022-07-13 05:19:11,287] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:19:11,287] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:19:11,299] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:19:42,287] {processor.py:163} INFO - Started process (PID=1476) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:19:42,288] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:19:42,288] {logging_mixin.py:109} INFO - [2022-07-13 05:19:42,288] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:19:42,289] {logging_mixin.py:109} INFO - [2022-07-13 05:19:42,289] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:19:42,289] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:19:42,301] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:20:13,197] {processor.py:163} INFO - Started process (PID=1547) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:20:13,198] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:20:13,199] {logging_mixin.py:109} INFO - [2022-07-13 05:20:13,198] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:20:13,200] {logging_mixin.py:109} INFO - [2022-07-13 05:20:13,200] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:20:13,200] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:20:13,213] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.018 seconds
[2022-07-13 05:20:44,130] {processor.py:163} INFO - Started process (PID=1611) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:20:44,131] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:20:44,131] {logging_mixin.py:109} INFO - [2022-07-13 05:20:44,131] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:20:44,133] {logging_mixin.py:109} INFO - [2022-07-13 05:20:44,132] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:20:44,133] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:20:44,145] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.017 seconds
[2022-07-13 05:21:14,902] {processor.py:163} INFO - Started process (PID=1684) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:21:14,903] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:21:14,903] {logging_mixin.py:109} INFO - [2022-07-13 05:21:14,903] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:21:14,904] {logging_mixin.py:109} INFO - [2022-07-13 05:21:14,904] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:21:14,904] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:21:14,916] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:21:45,017] {processor.py:163} INFO - Started process (PID=1758) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:21:45,017] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:21:45,018] {logging_mixin.py:109} INFO - [2022-07-13 05:21:45,018] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:21:45,019] {logging_mixin.py:109} INFO - [2022-07-13 05:21:45,019] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:21:45,019] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:21:45,031] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:22:15,900] {processor.py:163} INFO - Started process (PID=1821) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:22:15,901] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:22:15,901] {logging_mixin.py:109} INFO - [2022-07-13 05:22:15,901] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:22:15,902] {logging_mixin.py:109} INFO - [2022-07-13 05:22:15,902] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:22:15,902] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:22:15,913] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.014 seconds
[2022-07-13 05:22:46,595] {processor.py:163} INFO - Started process (PID=1892) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:22:46,596] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:22:46,596] {logging_mixin.py:109} INFO - [2022-07-13 05:22:46,596] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:22:46,597] {logging_mixin.py:109} INFO - [2022-07-13 05:22:46,597] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:22:46,598] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:22:46,608] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.014 seconds
[2022-07-13 05:23:17,589] {processor.py:163} INFO - Started process (PID=1963) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:23:17,590] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:23:17,590] {logging_mixin.py:109} INFO - [2022-07-13 05:23:17,590] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:23:17,591] {logging_mixin.py:109} INFO - [2022-07-13 05:23:17,591] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:23:17,592] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:23:17,603] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:23:47,704] {processor.py:163} INFO - Started process (PID=2025) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:23:47,705] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:23:47,705] {logging_mixin.py:109} INFO - [2022-07-13 05:23:47,705] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:23:47,706] {logging_mixin.py:109} INFO - [2022-07-13 05:23:47,706] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:23:47,706] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:23:47,716] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.014 seconds
[2022-07-13 05:24:18,547] {processor.py:163} INFO - Started process (PID=2096) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:24:18,548] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:24:18,548] {logging_mixin.py:109} INFO - [2022-07-13 05:24:18,548] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:24:18,549] {logging_mixin.py:109} INFO - [2022-07-13 05:24:18,549] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:24:18,549] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:24:18,560] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.014 seconds
[2022-07-13 05:24:49,296] {processor.py:163} INFO - Started process (PID=2168) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:24:49,297] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:24:49,297] {logging_mixin.py:109} INFO - [2022-07-13 05:24:49,297] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:24:49,299] {logging_mixin.py:109} INFO - [2022-07-13 05:24:49,298] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:24:49,299] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:24:49,309] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.014 seconds
[2022-07-13 05:25:20,180] {processor.py:163} INFO - Started process (PID=2240) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:25:20,181] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:25:20,181] {logging_mixin.py:109} INFO - [2022-07-13 05:25:20,181] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:25:20,183] {logging_mixin.py:109} INFO - [2022-07-13 05:25:20,182] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:25:20,183] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:25:20,195] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:25:50,943] {processor.py:163} INFO - Started process (PID=2302) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:25:50,943] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:25:50,944] {logging_mixin.py:109} INFO - [2022-07-13 05:25:50,943] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:25:50,945] {logging_mixin.py:109} INFO - [2022-07-13 05:25:50,944] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:25:50,945] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:25:50,957] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:26:21,915] {processor.py:163} INFO - Started process (PID=2373) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:26:21,915] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:26:21,915] {logging_mixin.py:109} INFO - [2022-07-13 05:26:21,915] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:26:21,917] {logging_mixin.py:109} INFO - [2022-07-13 05:26:21,916] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:26:21,917] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:26:21,928] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:26:52,821] {processor.py:163} INFO - Started process (PID=2445) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:26:52,822] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:26:52,822] {logging_mixin.py:109} INFO - [2022-07-13 05:26:52,822] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:26:52,823] {logging_mixin.py:109} INFO - [2022-07-13 05:26:52,823] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:26:52,823] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:26:52,841] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.022 seconds
[2022-07-13 05:27:23,798] {processor.py:163} INFO - Started process (PID=2508) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:27:23,799] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:27:23,799] {logging_mixin.py:109} INFO - [2022-07-13 05:27:23,799] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:27:23,800] {logging_mixin.py:109} INFO - [2022-07-13 05:27:23,800] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:27:23,800] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:27:23,811] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:27:54,688] {processor.py:163} INFO - Started process (PID=2579) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:27:54,689] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:27:54,689] {logging_mixin.py:109} INFO - [2022-07-13 05:27:54,689] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:27:54,690] {logging_mixin.py:109} INFO - [2022-07-13 05:27:54,690] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:27:54,690] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:27:54,700] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.014 seconds
[2022-07-13 05:28:25,512] {processor.py:163} INFO - Started process (PID=2650) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:28:25,513] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:28:25,513] {logging_mixin.py:109} INFO - [2022-07-13 05:28:25,513] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:28:25,514] {logging_mixin.py:109} INFO - [2022-07-13 05:28:25,514] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:28:25,514] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:28:25,525] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:28:56,440] {processor.py:163} INFO - Started process (PID=2713) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:28:56,441] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:28:56,441] {logging_mixin.py:109} INFO - [2022-07-13 05:28:56,441] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:28:56,442] {logging_mixin.py:109} INFO - [2022-07-13 05:28:56,442] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:28:56,442] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:28:56,455] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:29:27,264] {processor.py:163} INFO - Started process (PID=2784) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:29:27,265] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:29:27,265] {logging_mixin.py:109} INFO - [2022-07-13 05:29:27,265] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:29:27,267] {logging_mixin.py:109} INFO - [2022-07-13 05:29:27,266] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:29:27,267] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:29:27,279] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:29:58,189] {processor.py:163} INFO - Started process (PID=2856) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:29:58,190] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:29:58,190] {logging_mixin.py:109} INFO - [2022-07-13 05:29:58,190] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:29:58,192] {logging_mixin.py:109} INFO - [2022-07-13 05:29:58,191] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:29:58,192] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:29:58,203] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:30:29,119] {processor.py:163} INFO - Started process (PID=2917) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:30:29,120] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:30:29,120] {logging_mixin.py:109} INFO - [2022-07-13 05:30:29,120] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:30:29,121] {logging_mixin.py:109} INFO - [2022-07-13 05:30:29,121] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:30:29,122] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:30:29,133] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:30:59,974] {processor.py:163} INFO - Started process (PID=2989) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:30:59,975] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:30:59,975] {logging_mixin.py:109} INFO - [2022-07-13 05:30:59,975] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:30:59,977] {logging_mixin.py:109} INFO - [2022-07-13 05:30:59,976] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:30:59,977] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:30:59,989] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:31:30,039] {processor.py:163} INFO - Started process (PID=3060) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:31:30,040] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:31:30,041] {logging_mixin.py:109} INFO - [2022-07-13 05:31:30,040] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:31:30,042] {logging_mixin.py:109} INFO - [2022-07-13 05:31:30,041] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:31:30,042] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:31:30,055] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.017 seconds
[2022-07-13 05:32:00,403] {processor.py:163} INFO - Started process (PID=3122) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:32:00,404] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:32:00,404] {logging_mixin.py:109} INFO - [2022-07-13 05:32:00,404] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:32:00,405] {logging_mixin.py:109} INFO - [2022-07-13 05:32:00,405] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:32:00,406] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:32:00,417] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:32:30,434] {processor.py:163} INFO - Started process (PID=3195) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:32:30,435] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:32:30,435] {logging_mixin.py:109} INFO - [2022-07-13 05:32:30,435] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:32:30,437] {logging_mixin.py:109} INFO - [2022-07-13 05:32:30,437] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:32:30,438] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:32:30,453] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.022 seconds
[2022-07-13 05:33:01,449] {processor.py:163} INFO - Started process (PID=3268) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:33:01,450] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:33:01,451] {logging_mixin.py:109} INFO - [2022-07-13 05:33:01,451] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:33:01,454] {logging_mixin.py:109} INFO - [2022-07-13 05:33:01,453] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:33:01,454] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:33:01,476] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.030 seconds
[2022-07-13 05:33:32,409] {processor.py:163} INFO - Started process (PID=3330) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:33:32,410] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:33:32,410] {logging_mixin.py:109} INFO - [2022-07-13 05:33:32,410] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:33:32,411] {logging_mixin.py:109} INFO - [2022-07-13 05:33:32,411] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:33:32,412] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:33:32,426] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.019 seconds
[2022-07-13 05:34:03,298] {processor.py:163} INFO - Started process (PID=3401) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:34:03,298] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:34:03,299] {logging_mixin.py:109} INFO - [2022-07-13 05:34:03,299] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:34:03,300] {logging_mixin.py:109} INFO - [2022-07-13 05:34:03,300] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:34:03,300] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:34:03,312] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:34:34,109] {processor.py:163} INFO - Started process (PID=3472) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:34:34,110] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:34:34,110] {logging_mixin.py:109} INFO - [2022-07-13 05:34:34,110] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:34:34,111] {logging_mixin.py:109} INFO - [2022-07-13 05:34:34,111] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:34:34,112] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:34:34,123] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:35:04,906] {processor.py:163} INFO - Started process (PID=3534) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:35:04,907] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:35:04,907] {logging_mixin.py:109} INFO - [2022-07-13 05:35:04,907] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:35:04,909] {logging_mixin.py:109} INFO - [2022-07-13 05:35:04,908] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:35:04,909] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:35:04,920] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:35:35,770] {processor.py:163} INFO - Started process (PID=3606) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:35:35,771] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:35:35,771] {logging_mixin.py:109} INFO - [2022-07-13 05:35:35,771] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:35:35,772] {logging_mixin.py:109} INFO - [2022-07-13 05:35:35,772] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:35:35,773] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:35:35,784] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:36:06,741] {processor.py:163} INFO - Started process (PID=3680) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:36:06,742] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:36:06,742] {logging_mixin.py:109} INFO - [2022-07-13 05:36:06,742] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:36:06,744] {logging_mixin.py:109} INFO - [2022-07-13 05:36:06,743] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:36:06,744] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:36:06,757] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.018 seconds
[2022-07-13 05:36:36,950] {processor.py:163} INFO - Started process (PID=3742) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:36:36,950] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:36:36,951] {logging_mixin.py:109} INFO - [2022-07-13 05:36:36,950] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:36:36,952] {logging_mixin.py:109} INFO - [2022-07-13 05:36:36,951] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:36:36,952] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:36:36,964] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:37:07,229] {processor.py:163} INFO - Started process (PID=3816) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:37:07,230] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:37:07,230] {logging_mixin.py:109} INFO - [2022-07-13 05:37:07,230] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:37:07,231] {logging_mixin.py:109} INFO - [2022-07-13 05:37:07,231] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:37:07,232] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:37:07,243] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:37:37,822] {processor.py:163} INFO - Started process (PID=3887) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:37:37,822] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:37:37,823] {logging_mixin.py:109} INFO - [2022-07-13 05:37:37,823] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:37:37,824] {logging_mixin.py:109} INFO - [2022-07-13 05:37:37,824] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:37:37,824] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:37:37,836] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:38:08,471] {processor.py:163} INFO - Started process (PID=3949) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:38:08,471] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:38:08,472] {logging_mixin.py:109} INFO - [2022-07-13 05:38:08,472] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:38:08,473] {logging_mixin.py:109} INFO - [2022-07-13 05:38:08,473] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:38:08,473] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:38:08,485] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:38:39,335] {processor.py:163} INFO - Started process (PID=4020) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:38:39,335] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:38:39,335] {logging_mixin.py:109} INFO - [2022-07-13 05:38:39,335] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:38:39,337] {logging_mixin.py:109} INFO - [2022-07-13 05:38:39,336] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:38:39,337] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:38:39,348] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:39:09,899] {processor.py:163} INFO - Started process (PID=4092) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:39:09,900] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:39:09,900] {logging_mixin.py:109} INFO - [2022-07-13 05:39:09,900] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:39:09,902] {logging_mixin.py:109} INFO - [2022-07-13 05:39:09,901] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:39:09,902] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:39:09,914] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:39:40,775] {processor.py:163} INFO - Started process (PID=4156) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:39:40,775] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:39:40,776] {logging_mixin.py:109} INFO - [2022-07-13 05:39:40,776] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:39:40,777] {logging_mixin.py:109} INFO - [2022-07-13 05:39:40,777] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:39:40,777] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:39:40,789] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:40:11,430] {processor.py:163} INFO - Started process (PID=4228) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:40:11,430] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:40:11,431] {logging_mixin.py:109} INFO - [2022-07-13 05:40:11,431] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:40:11,432] {logging_mixin.py:109} INFO - [2022-07-13 05:40:11,431] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:40:11,432] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:40:11,444] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:40:42,252] {processor.py:163} INFO - Started process (PID=4300) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:40:42,252] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:40:42,253] {logging_mixin.py:109} INFO - [2022-07-13 05:40:42,253] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:40:42,254] {logging_mixin.py:109} INFO - [2022-07-13 05:40:42,254] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:40:42,254] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:40:42,266] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:41:12,867] {processor.py:163} INFO - Started process (PID=4363) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:41:12,868] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:41:12,868] {logging_mixin.py:109} INFO - [2022-07-13 05:41:12,868] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:41:12,870] {logging_mixin.py:109} INFO - [2022-07-13 05:41:12,869] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:41:12,870] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:41:12,881] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:41:43,724] {processor.py:163} INFO - Started process (PID=4434) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:41:43,725] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:41:43,725] {logging_mixin.py:109} INFO - [2022-07-13 05:41:43,725] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:41:43,726] {logging_mixin.py:109} INFO - [2022-07-13 05:41:43,726] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:41:43,726] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:41:43,740] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.018 seconds
[2022-07-13 05:42:14,524] {processor.py:163} INFO - Started process (PID=4505) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:42:14,525] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:42:14,525] {logging_mixin.py:109} INFO - [2022-07-13 05:42:14,525] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:42:14,527] {logging_mixin.py:109} INFO - [2022-07-13 05:42:14,526] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:42:14,527] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:42:14,540] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.017 seconds
[2022-07-13 05:42:45,282] {processor.py:163} INFO - Started process (PID=4567) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:42:45,282] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:42:45,283] {logging_mixin.py:109} INFO - [2022-07-13 05:42:45,283] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:42:45,284] {logging_mixin.py:109} INFO - [2022-07-13 05:42:45,284] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:42:45,284] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:42:45,353] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.073 seconds
[2022-07-13 05:43:16,362] {processor.py:163} INFO - Started process (PID=4638) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:43:16,363] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:43:16,363] {logging_mixin.py:109} INFO - [2022-07-13 05:43:16,363] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:43:16,364] {logging_mixin.py:109} INFO - [2022-07-13 05:43:16,364] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:43:16,365] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:43:16,433] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.073 seconds
[2022-07-13 05:43:47,285] {processor.py:163} INFO - Started process (PID=4712) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:43:47,286] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:43:47,286] {logging_mixin.py:109} INFO - [2022-07-13 05:43:47,286] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:43:47,288] {logging_mixin.py:109} INFO - [2022-07-13 05:43:47,287] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:43:47,288] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:43:47,303] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.020 seconds
[2022-07-13 05:44:17,946] {processor.py:163} INFO - Started process (PID=4775) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:44:17,947] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:44:17,947] {logging_mixin.py:109} INFO - [2022-07-13 05:44:17,947] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:44:17,949] {logging_mixin.py:109} INFO - [2022-07-13 05:44:17,948] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:44:17,949] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:44:17,960] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:44:48,619] {processor.py:163} INFO - Started process (PID=4847) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:44:48,619] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:44:48,620] {logging_mixin.py:109} INFO - [2022-07-13 05:44:48,620] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:44:48,621] {logging_mixin.py:109} INFO - [2022-07-13 05:44:48,621] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:44:48,621] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:44:48,633] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:45:19,282] {processor.py:163} INFO - Started process (PID=4919) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:45:19,283] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:45:19,283] {logging_mixin.py:109} INFO - [2022-07-13 05:45:19,283] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:45:19,284] {logging_mixin.py:109} INFO - [2022-07-13 05:45:19,284] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:45:19,285] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:45:19,296] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.015 seconds
[2022-07-13 05:45:49,806] {processor.py:163} INFO - Started process (PID=4991) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:45:49,807] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:45:49,807] {logging_mixin.py:109} INFO - [2022-07-13 05:45:49,807] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:45:49,809] {logging_mixin.py:109} INFO - [2022-07-13 05:45:49,808] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:45:49,809] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:45:49,821] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:46:20,552] {processor.py:163} INFO - Started process (PID=5056) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:46:20,553] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:46:20,553] {logging_mixin.py:109} INFO - [2022-07-13 05:46:20,553] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:46:20,555] {logging_mixin.py:109} INFO - [2022-07-13 05:46:20,554] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:46:20,555] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:46:20,571] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.021 seconds
[2022-07-13 05:46:51,166] {processor.py:163} INFO - Started process (PID=5128) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:46:51,166] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:46:51,167] {logging_mixin.py:109} INFO - [2022-07-13 05:46:51,166] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:46:51,168] {logging_mixin.py:109} INFO - [2022-07-13 05:46:51,167] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:46:51,168] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:46:51,180] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:47:21,718] {processor.py:163} INFO - Started process (PID=5190) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:47:21,718] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:47:21,719] {logging_mixin.py:109} INFO - [2022-07-13 05:47:21,719] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:47:21,720] {logging_mixin.py:109} INFO - [2022-07-13 05:47:21,719] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:47:21,720] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:47:21,736] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.020 seconds
[2022-07-13 05:47:52,519] {processor.py:163} INFO - Started process (PID=5262) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:47:52,520] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:47:52,520] {logging_mixin.py:109} INFO - [2022-07-13 05:47:52,520] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:47:52,522] {logging_mixin.py:109} INFO - [2022-07-13 05:47:52,521] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:47:52,522] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:47:52,533] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:48:23,234] {processor.py:163} INFO - Started process (PID=5334) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:48:23,234] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:48:23,235] {logging_mixin.py:109} INFO - [2022-07-13 05:48:23,235] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:48:23,236] {logging_mixin.py:109} INFO - [2022-07-13 05:48:23,236] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:48:23,237] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:48:23,250] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.018 seconds
[2022-07-13 05:48:53,834] {processor.py:163} INFO - Started process (PID=5397) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:48:53,835] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:48:53,835] {logging_mixin.py:109} INFO - [2022-07-13 05:48:53,835] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:48:53,837] {logging_mixin.py:109} INFO - [2022-07-13 05:48:53,836] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:48:53,837] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:48:53,848] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:49:24,621] {processor.py:163} INFO - Started process (PID=5469) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:49:24,622] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:49:24,622] {logging_mixin.py:109} INFO - [2022-07-13 05:49:24,622] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:49:24,624] {logging_mixin.py:109} INFO - [2022-07-13 05:49:24,623] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:49:24,624] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:49:24,637] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.018 seconds
[2022-07-13 05:50:00,423] {processor.py:163} INFO - Started process (PID=36) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:50:00,424] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:50:00,424] {logging_mixin.py:109} INFO - [2022-07-13 05:50:00,424] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:50:00,426] {logging_mixin.py:109} INFO - [2022-07-13 05:50:00,425] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:50:00,426] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:50:00,443] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.022 seconds
[2022-07-13 05:50:31,069] {processor.py:163} INFO - Started process (PID=107) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:50:31,070] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:50:31,070] {logging_mixin.py:109} INFO - [2022-07-13 05:50:31,070] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:50:31,071] {logging_mixin.py:109} INFO - [2022-07-13 05:50:31,071] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:50:31,071] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:50:31,085] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.017 seconds
[2022-07-13 05:51:02,005] {processor.py:163} INFO - Started process (PID=180) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:51:02,005] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:51:02,006] {logging_mixin.py:109} INFO - [2022-07-13 05:51:02,006] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:51:02,007] {logging_mixin.py:109} INFO - [2022-07-13 05:51:02,007] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:51:02,007] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:51:02,023] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.020 seconds
[2022-07-13 05:51:32,051] {processor.py:163} INFO - Started process (PID=241) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:51:32,051] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:51:32,051] {logging_mixin.py:109} INFO - [2022-07-13 05:51:32,051] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:51:32,053] {logging_mixin.py:109} INFO - [2022-07-13 05:51:32,052] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:51:32,053] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:51:32,064] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:52:02,239] {processor.py:163} INFO - Started process (PID=313) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:52:02,239] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:52:02,240] {logging_mixin.py:109} INFO - [2022-07-13 05:52:02,240] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:52:02,241] {logging_mixin.py:109} INFO - [2022-07-13 05:52:02,241] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:52:02,241] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:52:02,254] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.017 seconds
[2022-07-13 05:52:33,080] {processor.py:163} INFO - Started process (PID=395) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:52:33,081] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:52:33,081] {logging_mixin.py:109} INFO - [2022-07-13 05:52:33,081] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:52:33,083] {logging_mixin.py:109} INFO - [2022-07-13 05:52:33,082] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:52:33,083] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:52:33,098] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.019 seconds
[2022-07-13 05:53:03,904] {processor.py:163} INFO - Started process (PID=458) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:53:03,905] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:53:03,905] {logging_mixin.py:109} INFO - [2022-07-13 05:53:03,905] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:53:03,907] {logging_mixin.py:109} INFO - [2022-07-13 05:53:03,907] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:53:03,907] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:53:03,963] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.061 seconds
[2022-07-13 05:53:34,257] {processor.py:163} INFO - Started process (PID=529) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:53:34,258] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:53:34,258] {logging_mixin.py:109} INFO - [2022-07-13 05:53:34,258] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:53:34,259] {logging_mixin.py:109} INFO - [2022-07-13 05:53:34,259] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:53:34,260] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:53:34,271] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:54:04,360] {processor.py:163} INFO - Started process (PID=592) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:54:04,360] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:54:04,361] {logging_mixin.py:109} INFO - [2022-07-13 05:54:04,361] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:54:04,362] {logging_mixin.py:109} INFO - [2022-07-13 05:54:04,362] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:54:04,362] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:54:04,374] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:54:34,394] {processor.py:163} INFO - Started process (PID=665) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:54:34,394] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:54:34,395] {logging_mixin.py:109} INFO - [2022-07-13 05:54:34,395] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:54:34,396] {logging_mixin.py:109} INFO - [2022-07-13 05:54:34,396] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:54:34,396] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:54:34,408] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:55:05,249] {processor.py:163} INFO - Started process (PID=737) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:55:05,250] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:55:05,250] {logging_mixin.py:109} INFO - [2022-07-13 05:55:05,250] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:55:05,251] {logging_mixin.py:109} INFO - [2022-07-13 05:55:05,251] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:55:05,252] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:55:05,263] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.016 seconds
[2022-07-13 05:55:35,985] {processor.py:163} INFO - Started process (PID=799) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:55:35,985] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:55:35,986] {logging_mixin.py:109} INFO - [2022-07-13 05:55:35,986] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:55:35,987] {logging_mixin.py:109} INFO - [2022-07-13 05:55:35,987] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:55:35,987] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:55:36,000] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.017 seconds
[2022-07-13 05:56:06,775] {processor.py:163} INFO - Started process (PID=870) to work on /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:56:06,776] {processor.py:642} INFO - Processing file /opt/airflow/dags/tests/dags/pyfixture.py for tasks to queue
[2022-07-13 05:56:06,776] {logging_mixin.py:109} INFO - [2022-07-13 05:56:06,776] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:56:06,778] {logging_mixin.py:109} INFO - [2022-07-13 05:56:06,777] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/tests/dags/pyfixture.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tests/dags/pyfixture.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2022-07-13 05:56:06,778] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/tests/dags/pyfixture.py
[2022-07-13 05:56:06,790] {processor.py:171} INFO - Processing /opt/airflow/dags/tests/dags/pyfixture.py took 0.017 seconds
