[2022-07-04 05:34:51,278] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-07-03T00:00:00+00:00 [queued]>
[2022-07-04 05:34:51,285] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-07-03T00:00:00+00:00 [queued]>
[2022-07-04 05:34:51,285] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 05:34:51,285] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-07-04 05:34:51,285] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 05:34:51,291] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-07-03 00:00:00+00:00
[2022-07-04 05:34:51,295] {standard_task_runner.py:52} INFO - Started process 2103 to run task
[2022-07-04 05:34:51,298] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-07-03T00:00:00+00:00', '--job-id', '440', '--raw', '--subdir', 'DAGS_FOLDER/model.py', '--cfg-path', '/tmp/tmpnvte16ae', '--error-file', '/tmp/tmphqucjthi']
[2022-07-04 05:34:51,298] {standard_task_runner.py:80} INFO - Job 440: Subtask inaccurate
[2022-07-04 05:34:51,331] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-07-03T00:00:00+00:00 [running]> on host 1936d03cc531
[2022-07-04 05:34:51,362] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-03T00:00:00+00:00
[2022-07-04 05:34:51,362] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-04 05:34:51,363] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo  'inaccurate' "]
[2022-07-04 05:34:51,370] {subprocess.py:85} INFO - Output:
[2022-07-04 05:34:51,371] {subprocess.py:89} INFO - inaccurate
[2022-07-04 05:34:51,371] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-04 05:34:51,387] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220703T000000, start_date=20220704T053451, end_date=20220704T053451
[2022-07-04 05:34:51,430] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-04 05:34:51,450] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
