[2022-07-04 12:27:02,319] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-07-04T12:26:59.541504+00:00 [queued]>
[2022-07-04 12:27:02,328] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-07-04T12:26:59.541504+00:00 [queued]>
[2022-07-04 12:27:02,328] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 12:27:02,328] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-07-04 12:27:02,328] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-07-04 12:27:02,336] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-07-04 12:26:59.541504+00:00
[2022-07-04 12:27:02,341] {standard_task_runner.py:52} INFO - Started process 723 to run task
[2022-07-04 12:27:02,343] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2022-07-04T12:26:59.541504+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/model.py', '--cfg-path', '/tmp/tmpbbgnmj1v', '--error-file', '/tmp/tmptaucj_gr']
[2022-07-04 12:27:02,343] {standard_task_runner.py:80} INFO - Job 28: Subtask inaccurate
[2022-07-04 12:27:02,383] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate manual__2022-07-04T12:26:59.541504+00:00 [running]> on host 498c2b9fabaa
[2022-07-04 12:27:02,422] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-04T12:26:59.541504+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-04T12:26:59.541504+00:00
[2022-07-04 12:27:02,422] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-04 12:27:02,423] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo  'inaccurate' "]
[2022-07-04 12:27:02,432] {subprocess.py:85} INFO - Output:
[2022-07-04 12:27:02,433] {subprocess.py:89} INFO - inaccurate
[2022-07-04 12:27:02,433] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-04 12:27:02,449] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220704T122659, start_date=20220704T122702, end_date=20220704T122702
[2022-07-04 12:27:02,474] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-04 12:27:02,493] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
