[2022-07-04 04:41:50,379] {processor.py:163} INFO - Started process (PID=29) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:41:50,379] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 04:41:50,380] {logging_mixin.py:109} INFO - [2022-07-04 04:41:50,379] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:41:50,384] {logging_mixin.py:109} INFO - [2022-07-04 04:41:50,383] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 04:41:50,384] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:41:50,397] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.020 seconds
[2022-07-04 04:42:21,187] {processor.py:163} INFO - Started process (PID=91) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:42:21,188] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 04:42:21,188] {logging_mixin.py:109} INFO - [2022-07-04 04:42:21,188] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:42:21,191] {logging_mixin.py:109} INFO - [2022-07-04 04:42:21,191] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 04:42:21,192] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:42:21,203] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.018 seconds
[2022-07-04 04:42:51,909] {processor.py:163} INFO - Started process (PID=141) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:42:51,910] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 04:42:51,910] {logging_mixin.py:109} INFO - [2022-07-04 04:42:51,910] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:42:51,913] {logging_mixin.py:109} INFO - [2022-07-04 04:42:51,913] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 04:42:51,914] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:42:51,930] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.023 seconds
[2022-07-04 04:43:22,046] {processor.py:163} INFO - Started process (PID=202) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:43:22,047] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 04:43:22,047] {logging_mixin.py:109} INFO - [2022-07-04 04:43:22,047] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:43:22,051] {logging_mixin.py:109} INFO - [2022-07-04 04:43:22,050] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 04:43:22,051] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:43:22,063] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.018 seconds
[2022-07-04 04:43:52,587] {processor.py:163} INFO - Started process (PID=263) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:43:52,587] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 04:43:52,588] {logging_mixin.py:109} INFO - [2022-07-04 04:43:52,588] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:43:52,591] {logging_mixin.py:109} INFO - [2022-07-04 04:43:52,591] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 04:43:52,591] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:43:52,603] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.019 seconds
[2022-07-04 04:44:23,036] {processor.py:163} INFO - Started process (PID=315) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:44:23,038] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 04:44:23,038] {logging_mixin.py:109} INFO - [2022-07-04 04:44:23,038] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:44:23,045] {logging_mixin.py:109} INFO - [2022-07-04 04:44:23,044] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 04:44:23,045] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:44:23,058] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.024 seconds
[2022-07-04 04:44:53,646] {processor.py:163} INFO - Started process (PID=375) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:44:53,647] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 04:44:53,648] {logging_mixin.py:109} INFO - [2022-07-04 04:44:53,648] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:44:53,651] {logging_mixin.py:109} INFO - [2022-07-04 04:44:53,651] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 04:44:53,651] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:44:53,664] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.020 seconds
[2022-07-04 04:45:24,130] {processor.py:163} INFO - Started process (PID=436) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:45:24,130] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 04:45:24,130] {logging_mixin.py:109} INFO - [2022-07-04 04:45:24,130] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:45:24,137] {logging_mixin.py:109} INFO - [2022-07-04 04:45:24,136] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 04:45:24,137] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:45:24,148] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.021 seconds
[2022-07-04 04:45:54,558] {processor.py:163} INFO - Started process (PID=487) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:45:54,559] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 04:45:54,560] {logging_mixin.py:109} INFO - [2022-07-04 04:45:54,560] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:45:54,567] {logging_mixin.py:109} INFO - [2022-07-04 04:45:54,567] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 04:45:54,568] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:45:54,580] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.024 seconds
[2022-07-04 04:58:15,872] {processor.py:163} INFO - Started process (PID=30) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:58:15,873] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 04:58:15,873] {logging_mixin.py:109} INFO - [2022-07-04 04:58:15,873] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:58:15,880] {logging_mixin.py:109} INFO - [2022-07-04 04:58:15,880] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 04:58:15,880] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:58:15,894] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.023 seconds
[2022-07-04 04:58:46,112] {processor.py:163} INFO - Started process (PID=330) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:58:46,112] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 04:58:46,113] {logging_mixin.py:109} INFO - [2022-07-04 04:58:46,113] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:58:46,116] {logging_mixin.py:109} INFO - [2022-07-04 04:58:46,116] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 04:58:46,117] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 04:58:46,133] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.024 seconds
[2022-07-04 05:01:38,510] {processor.py:163} INFO - Started process (PID=31) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:01:38,511] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:01:38,511] {logging_mixin.py:109} INFO - [2022-07-04 05:01:38,511] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:01:38,520] {logging_mixin.py:109} INFO - [2022-07-04 05:01:38,520] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:01:38,521] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:01:38,537] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.029 seconds
[2022-07-04 05:02:08,900] {processor.py:163} INFO - Started process (PID=331) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:02:08,900] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:02:08,901] {logging_mixin.py:109} INFO - [2022-07-04 05:02:08,901] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:02:08,903] {logging_mixin.py:109} INFO - [2022-07-04 05:02:08,903] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:02:08,904] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:02:08,922] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.023 seconds
[2022-07-04 05:02:39,735] {processor.py:163} INFO - Started process (PID=392) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:02:39,736] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:02:39,736] {logging_mixin.py:109} INFO - [2022-07-04 05:02:39,736] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:02:39,742] {logging_mixin.py:109} INFO - [2022-07-04 05:02:39,741] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:02:39,742] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:02:39,754] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.021 seconds
[2022-07-04 05:03:10,631] {processor.py:163} INFO - Started process (PID=444) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:03:10,632] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:03:10,632] {logging_mixin.py:109} INFO - [2022-07-04 05:03:10,632] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:03:10,639] {logging_mixin.py:109} INFO - [2022-07-04 05:03:10,639] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:03:10,640] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:03:10,653] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.025 seconds
[2022-07-04 05:03:40,827] {processor.py:163} INFO - Started process (PID=506) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:03:40,833] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:03:40,834] {logging_mixin.py:109} INFO - [2022-07-04 05:03:40,833] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:03:40,837] {logging_mixin.py:109} INFO - [2022-07-04 05:03:40,837] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:03:40,837] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:03:40,848] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.023 seconds
[2022-07-04 05:04:11,004] {processor.py:163} INFO - Started process (PID=567) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:04:11,010] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:04:11,010] {logging_mixin.py:109} INFO - [2022-07-04 05:04:11,010] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:04:11,014] {logging_mixin.py:109} INFO - [2022-07-04 05:04:11,013] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:04:11,014] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:04:11,027] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.025 seconds
[2022-07-04 05:04:41,177] {processor.py:163} INFO - Started process (PID=619) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:04:41,184] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:04:41,185] {logging_mixin.py:109} INFO - [2022-07-04 05:04:41,185] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:04:41,191] {logging_mixin.py:109} INFO - [2022-07-04 05:04:41,190] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:04:41,191] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:04:41,209] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.033 seconds
[2022-07-04 05:05:11,412] {processor.py:163} INFO - Started process (PID=679) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:05:11,418] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:05:11,419] {logging_mixin.py:109} INFO - [2022-07-04 05:05:11,419] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:05:11,424] {logging_mixin.py:109} INFO - [2022-07-04 05:05:11,424] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:05:11,425] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:05:11,439] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.029 seconds
[2022-07-04 05:05:41,662] {processor.py:163} INFO - Started process (PID=737) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:05:41,663] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:05:41,663] {logging_mixin.py:109} INFO - [2022-07-04 05:05:41,663] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:05:41,667] {logging_mixin.py:109} INFO - [2022-07-04 05:05:41,666] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:05:41,667] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:05:41,678] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.018 seconds
[2022-07-04 05:06:12,019] {processor.py:163} INFO - Started process (PID=790) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:06:12,026] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:06:12,026] {logging_mixin.py:109} INFO - [2022-07-04 05:06:12,026] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:06:12,031] {logging_mixin.py:109} INFO - [2022-07-04 05:06:12,031] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:06:12,032] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:06:12,054] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.037 seconds
[2022-07-04 05:06:42,253] {processor.py:163} INFO - Started process (PID=852) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:06:42,253] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:06:42,254] {logging_mixin.py:109} INFO - [2022-07-04 05:06:42,254] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:06:42,257] {logging_mixin.py:109} INFO - [2022-07-04 05:06:42,256] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:06:42,257] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:06:42,270] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.019 seconds
[2022-07-04 05:07:12,570] {processor.py:163} INFO - Started process (PID=903) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:07:12,571] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:07:12,571] {logging_mixin.py:109} INFO - [2022-07-04 05:07:12,571] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:07:12,575] {logging_mixin.py:109} INFO - [2022-07-04 05:07:12,575] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:07:12,576] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:07:12,587] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.019 seconds
[2022-07-04 05:07:42,817] {processor.py:163} INFO - Started process (PID=968) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:07:42,818] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:07:42,819] {logging_mixin.py:109} INFO - [2022-07-04 05:07:42,819] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:07:42,824] {logging_mixin.py:109} INFO - [2022-07-04 05:07:42,824] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:07:42,824] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:07:42,840] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.028 seconds
[2022-07-04 05:08:13,128] {processor.py:163} INFO - Started process (PID=1028) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:08:13,130] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:08:13,131] {logging_mixin.py:109} INFO - [2022-07-04 05:08:13,131] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:08:13,135] {logging_mixin.py:109} INFO - [2022-07-04 05:08:13,135] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:08:13,135] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:08:13,146] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.022 seconds
[2022-07-04 05:08:43,360] {processor.py:163} INFO - Started process (PID=1080) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:08:43,361] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:08:43,362] {logging_mixin.py:109} INFO - [2022-07-04 05:08:43,362] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:08:43,366] {logging_mixin.py:109} INFO - [2022-07-04 05:08:43,365] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:08:43,366] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:08:43,379] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.021 seconds
[2022-07-04 05:09:13,741] {processor.py:163} INFO - Started process (PID=1141) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:09:13,742] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:09:13,742] {logging_mixin.py:109} INFO - [2022-07-04 05:09:13,742] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:09:13,745] {logging_mixin.py:109} INFO - [2022-07-04 05:09:13,745] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:09:13,745] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:09:13,761] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.022 seconds
[2022-07-04 05:09:43,960] {processor.py:163} INFO - Started process (PID=1202) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:09:43,962] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:09:43,962] {logging_mixin.py:109} INFO - [2022-07-04 05:09:43,962] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:09:43,966] {logging_mixin.py:109} INFO - [2022-07-04 05:09:43,965] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:09:43,966] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:09:43,978] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.019 seconds
[2022-07-04 05:10:14,129] {processor.py:163} INFO - Started process (PID=1253) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:10:14,131] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:10:14,131] {logging_mixin.py:109} INFO - [2022-07-04 05:10:14,131] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:10:14,136] {logging_mixin.py:109} INFO - [2022-07-04 05:10:14,136] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:10:14,136] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:10:14,156] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.028 seconds
[2022-07-04 05:10:44,465] {processor.py:163} INFO - Started process (PID=1313) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:10:44,467] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:10:44,467] {logging_mixin.py:109} INFO - [2022-07-04 05:10:44,467] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:10:44,471] {logging_mixin.py:109} INFO - [2022-07-04 05:10:44,470] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:10:44,471] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:10:44,482] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.019 seconds
[2022-07-04 05:11:14,808] {processor.py:163} INFO - Started process (PID=1374) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:11:14,810] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:11:14,810] {logging_mixin.py:109} INFO - [2022-07-04 05:11:14,810] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:11:14,815] {logging_mixin.py:109} INFO - [2022-07-04 05:11:14,815] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:11:14,815] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:11:14,831] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.024 seconds
[2022-07-04 05:11:45,079] {processor.py:163} INFO - Started process (PID=1425) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:11:45,080] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:11:45,080] {logging_mixin.py:109} INFO - [2022-07-04 05:11:45,080] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:11:45,084] {logging_mixin.py:109} INFO - [2022-07-04 05:11:45,084] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:11:45,084] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:11:45,096] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.019 seconds
[2022-07-04 05:12:15,583] {processor.py:163} INFO - Started process (PID=1487) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:12:15,584] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:12:15,585] {logging_mixin.py:109} INFO - [2022-07-04 05:12:15,585] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:12:15,588] {logging_mixin.py:109} INFO - [2022-07-04 05:12:15,588] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:12:15,588] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:12:15,600] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.019 seconds
[2022-07-04 05:12:45,886] {processor.py:163} INFO - Started process (PID=1538) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:12:45,888] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:12:45,888] {logging_mixin.py:109} INFO - [2022-07-04 05:12:45,888] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:12:45,891] {logging_mixin.py:109} INFO - [2022-07-04 05:12:45,890] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:12:45,891] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:12:45,904] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.020 seconds
[2022-07-04 05:13:16,070] {processor.py:163} INFO - Started process (PID=1600) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:13:16,072] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:13:16,072] {logging_mixin.py:109} INFO - [2022-07-04 05:13:16,072] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:13:16,075] {logging_mixin.py:109} INFO - [2022-07-04 05:13:16,075] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:13:16,075] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:13:16,089] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.020 seconds
[2022-07-04 05:13:46,500] {processor.py:163} INFO - Started process (PID=1660) to work on /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:13:46,502] {processor.py:642} INFO - Processing file /opt/airflow/dags/postgres_demo.py for tasks to queue
[2022-07-04 05:13:46,502] {logging_mixin.py:109} INFO - [2022-07-04 05:13:46,502] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:13:46,506] {logging_mixin.py:109} INFO - [2022-07-04 05:13:46,505] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/postgres_demo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/postgres_demo.py", line 4, in <module>
    from airflow.operators.python_operator import PythonOpeator
ImportError: cannot import name 'PythonOpeator' from 'airflow.operators.python_operator' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py)
[2022-07-04 05:13:46,506] {processor.py:654} WARNING - No viable dags retrieved from /opt/airflow/dags/postgres_demo.py
[2022-07-04 05:13:46,520] {processor.py:171} INFO - Processing /opt/airflow/dags/postgres_demo.py took 0.021 seconds
