[2022-07-08 13:37:00,289] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-07-07T00:00:00+00:00 [queued]>
[2022-07-08 13:37:00,295] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-07-07T00:00:00+00:00 [queued]>
[2022-07-08 13:37:00,295] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-07-08 13:37:00,295] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-07-08 13:37:00,295] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-07-08 13:37:00,302] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-07-07 00:00:00+00:00
[2022-07-08 13:37:00,308] {standard_task_runner.py:52} INFO - Started process 596 to run task
[2022-07-08 13:37:00,310] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-07-07T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/model.py', '--cfg-path', '/tmp/tmpycrzeons', '--error-file', '/tmp/tmp7volp50_']
[2022-07-08 13:37:00,310] {standard_task_runner.py:80} INFO - Job 8: Subtask inaccurate
[2022-07-08 13:37:00,380] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-07-07T00:00:00+00:00 [running]> on host 18ea9465fe18
[2022-07-08 13:37:00,408] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-07T00:00:00+00:00
[2022-07-08 13:37:00,409] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-08 13:37:00,410] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo  'inaccurate' "]
[2022-07-08 13:37:00,418] {subprocess.py:85} INFO - Output:
[2022-07-08 13:37:00,419] {subprocess.py:89} INFO - inaccurate
[2022-07-08 13:37:00,420] {subprocess.py:93} INFO - Command exited with return code 0
[2022-07-08 13:37:00,434] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220707T000000, start_date=20220708T133700, end_date=20220708T133700
[2022-07-08 13:37:00,482] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-07-08 13:37:00,524] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
