[2022-06-27 07:23:41,189] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-06-26T00:00:00+00:00 [queued]>
[2022-06-27 07:23:41,197] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2022-06-26T00:00:00+00:00 [queued]>
[2022-06-27 07:23:41,197] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 07:23:41,197] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-06-27 07:23:41,197] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 07:23:41,204] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): inaccurate> on 2022-06-26 00:00:00+00:00
[2022-06-27 07:23:41,209] {standard_task_runner.py:52} INFO - Started process 1899 to run task
[2022-06-27 07:23:41,211] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2022-06-26T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/second_1.py', '--cfg-path', '/tmp/tmpwx6ebez4', '--error-file', '/tmp/tmp8vuhidw4']
[2022-06-27 07:23:41,211] {standard_task_runner.py:80} INFO - Job 86: Subtask inaccurate
[2022-06-27 07:23:41,245] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2022-06-26T00:00:00+00:00 [running]> on host f32f6d4577d5
[2022-06-27 07:23:41,277] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-06-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-26T00:00:00+00:00
[2022-06-27 07:23:41,278] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-27 07:23:41,279] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-06-27 07:23:41,287] {subprocess.py:85} INFO - Output:
[2022-06-27 07:23:41,288] {subprocess.py:89} INFO - inaccurate
[2022-06-27 07:23:41,289] {subprocess.py:93} INFO - Command exited with return code 0
[2022-06-27 07:23:41,305] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220626T000000, start_date=20220627T072341, end_date=20220627T072341
[2022-06-27 07:23:41,343] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-27 07:23:41,362] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
